modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "owo"
version = "${version}"
displayName = "oÏ‰o"
authors = "glisco, Blodhgarm, BasiqueEvangelist, Noaaan"
credits = ""
description = '''
yes its bad i know thanks
'''
logoFile = "assets/owo/icon.png"

[[mixins]]
config = 'owo.mixins.json'
[[mixins]]
config = 'owo-forge.mixins.json'

[[dependencies.owo]]
modId = "neoforge"
required = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.owo]]
modId = "minecraft"
required = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"